# Site settings
title: Kevin Chau
email: hello@kevinchau.me
description: "Kevin Chau | Growth at Divshot. Seattle native. Always learning."
baseurl: /
url: http://kevinchau.me
future: false
permalink: /:categories/:title
custom_paginate: 5
paginate_path: /blog/page:num

# Build settings
markdown: kramdown
permalink: none
